const fs = require('fs');
const content = `import { Service } from './types';

export const services: Service[] = [
  {
    id: 'income-certificate',
    categoryEn: 'Government Documents',
    categoryGu: 'સરકારી ડોક્યુમેન્ટ્સ',
    titleEn: 'Income Certificate',
    titleGu: 'આવકનો દાખલો',
    iconName: 'Award',
    descriptionEn: 'Income Certificate required for scholarship, admission, etc.',
    descriptionGu: 'આવકનો દાખલો સ્કોલરશિપ, એડમિશન વગેરે માટે જરૂરી છે.',
    documentsEn: ["Form and Photo", "Ration Card Copy", "School Leaving Certificate", "Talati\\'s Income Certificate", "Last Light Bill", "Aadhaar Card"],
    documentsGu: ["ફોર્મ અને ફોટો", "રેશન કાર્ડની નકલ", "સ્કુલ લીવીંગ સર્ટી", "તલાટીનો આવકનો દાખલો", "છેલ્લું લાઈટ બિલ", "આધારકાર્ડ"],
    popular: true
  },
  {
    id: 'caste-certificate',
    categoryEn: 'Government Documents',
    categoryGu: 'સરકારી ડોક્યુમેન્ટ્સ',
    titleEn: 'Caste Certificate',
    titleGu: 'જાતિનો દાખલો',
    iconName: 'Award',
    descriptionEn: 'Caste Certificate for educational and government purposes.',
    descriptionGu: 'શૈક્ષણિક અને સરકારી હેતુઓ માટે જાતિનો દાખલો.',
    documentsEn: ["Form and Photo", "Ration Card Copy", "School Leaving Certificate", "Father/Brother/Sister\\'s School Leaving", "Last Light Bill", "Talati\\'s Caste Certificate", "Aadhaar Card"],
    documentsGu: ["ફોર્મ અને ફોટો", "રેશન કાર્ડની નકલ", "સ્કુલ લીવીંગ સર્ટી", "પિતા / ભાઈ / બહેનનું સ્કુલ લીવીંગ", "છેલ્લું લાઈટ બિલ", "તલાટીનો જાતિનો દાખલો", "આધારકાર્ડ"],
    popular: true
  },
  {
    id: 'domicile-certificate',
    categoryEn: 'Government Documents',
    categoryGu: 'સરકારી ડોક્યુમેન્ટ્સ',
    titleEn: 'Domicile Certificate',
    titleGu: 'ડોમિસાઈલ સર્ટી',
    iconName: 'Award',
    descriptionEn: 'Domicile Certificate for proving residence in Gujarat state.',
    descriptionGu: 'ગુજરાત રાજ્યમાં રહેઠાણ સાબિત કરવા માટે ડોમિસાઈલ સર્ટી.',
    documentsEn: ["Form and Photo", "Ration Card Copy", "School Leaving Certificate", "Talati\\'s 10-year Residence Certificate", "Residence Affidavit (Sogandnamu)", "Last Light Bill", "Birth Certificate", "Police Station Certificate", "Aadhaar Card"],
    documentsGu: ["ફોર્મ અને ફોટો", "રેશન કાર્ડની નકલ", "સ્કુલ લીવીંગ સર્ટી", "તલાટીનો ૧૦ વર્ષનો રહેઠાણનો દાખલો", "રહેઠાણનું સોગંદનામું", "છેલ્લું લાઈટ બિલ", "જન્મનો દાખલો", "પોલીસ સ્ટેનો દાખલો", "આધારકાર્ડ"],
    popular: true
  },
  {
    id: 'ews-ncl-certificate',
    categoryEn: 'Government Documents',
    categoryGu: 'સરકારી ડોક્યુમેન્ટ્સ',
    titleEn: 'EWS / Non-Creamy Layer',
    titleGu: 'EWS / નોન-ક્રીમી લેયર દાખલો',
    iconName: 'Award',
    descriptionEn: 'EWS and Non-Creamy Layer certificates for unreserved/reserved categories.',
    descriptionGu: 'બિન-અનામત વર્ગ માટે EWS અને આરક્ષિત વર્ગ માટે નોન-ક્રીમી લેયર દાખલો.',
    documentsEn: ["Form and Photo", "Ration Card Copy", "School Leaving Certificate", "Income Certificate (Last 3 years for NCL)", "Talati\\'s Caste/EWS Certificate", "Last Light Bill", "Aadhaar Card"],
    documentsGu: ["ફોર્મ અને ફોટો", "રેશન કાર્ડની નકલ", "સ્કુલ લીવીંગ સર્ટી", "આવકનો દાખલો (NCL માટે છેલ્લા ૩ વર્ષનો)", "તલાટીનો દાખલો", "છેલ્લું લાઈટ બિલ", "આધારકાર્ડ"],
    popular: true
  },
  {
    id: 'ration-card',
    categoryEn: 'Government Documents',
    categoryGu: 'સરકારી ડોક્યુમેન્ટ્સ',
    titleEn: 'Ration Card Support',
    titleGu: 'રેશન કાર્ડ સંબંધિત કામગીરી',
    iconName: 'FileText',
    descriptionEn: 'Apply for new ration card, name addition/removal, and ration card correction.',
    descriptionGu: 'નવું રેશન કાર્ડ કઢાવવા, નામ ઉમેરવા/કમી કરવા, અને જરૂરી સુધારા કરવા.',
    documentsEn: ['Aadhaar Card of all members', 'Light Bill', 'Income Proof', 'Passport Photo', 'Old Ration Card (if any)'],
    documentsGu: ['પરિવારના તમામ સભ્યોના આધાર કાર્ડ', 'લાઈટ બિલ', 'આવકનો પુરાવો', 'પાસપોર્ટ ફોટો', 'જૂનું રેશન કાર્ડ (જો હોય તો)'],
    popular: true
  },
  {
    id: 'pancard',
    categoryEn: 'Identity & Registration',
    categoryGu: 'ઓળખ અને નોંધણી',
    titleEn: 'PAN Card Services',
    titleGu: 'પાન કાર્ડ',
    iconName: 'CreditCard',
    descriptionEn: 'New PAN Card application, corrections, or reprint services.',
    descriptionGu: 'નવું પાન કાર્ડ, પાન કાર્ડમાં સુધારો, અને ખોવાયેલ પાન કાર્ડ કઢાવવા.',
    documentsEn: ['Aadhaar Card', '2 Passport Size Photos'],
    documentsGu: ['આધાર કાર્ડ', '2 પાસપોર્ટ સાઈઝના ફોટા'],
    popular: true
  },
  {
    id: 'passport',
    categoryEn: 'Identity & Registration',
    categoryGu: 'ઓળખ અને નોંધણી',
    titleEn: 'Passport Appointment',
    titleGu: 'પાસપોર્ટ અરજી',
    iconName: 'Globe',
    descriptionEn: 'Apply for a fresh passport, reissue, or update passport details.',
    descriptionGu: 'નવા પાસપોર્ટ માટેની અરજી અને પાસપોર્ટ રીન્યુઅલ.',
    documentsEn: ['Aadhaar Card', 'Pan Card', 'Election Card', 'Leaving Certificate', '10th/12th Marksheet'],
    documentsGu: ['આધાર કાર્ડ', 'પાન કાર્ડ', 'ચૂંટણી કાર્ડ', 'LC (લીવીંગ સર્ટી)', '૧૦/૧૨ ની માર્કશીટ'],
    popular: true
  },
  {
    id: 'voter-id',
    categoryEn: 'Identity & Registration',
    categoryGu: 'ઓળખ અને નોંધણી',
    titleEn: 'Voter ID Services',
    titleGu: 'ચૂંટણી કાર્ડ',
    iconName: 'UserCheck',
    descriptionEn: 'Apply for a new Voter ID, correct details, or replace lost card.',
    descriptionGu: 'નવું ચૂંટણી કાર્ડ, સુધારો કરવા, અને પીવીસી કાર્ડ કઢાવવા.',
    documentsEn: ['Aadhaar Card', 'Passport Photo', 'Age Proof'],
    documentsGu: ['આધાર કાર્ડ', 'પાસપોર્ટ ફોટો', 'ઉંમરનો પુરાવો'],
    popular: false
  },
  {
    id: 'pf-withdrawal',
    categoryEn: 'Financial & Business',
    categoryGu: 'નાણાકીય અને વ્યાપારી',
    titleEn: 'PF Withdrawal',
    titleGu: 'PF ઉપાડ',
    iconName: 'Briefcase',
    descriptionEn: 'Online PF withdrawal, KYC update, UAN activation.',
    descriptionGu: 'PF ઉપાડવાની અરજી, KYC અપડેટ, UAN એક્ટિવેશન.',
    documentsEn: ['UAN Number', 'Password', 'Aadhaar Linked Mobile', 'Bank Passbook'],
    documentsGu: ['UAN નંબર', 'પાસવર્ડ', 'આધાર સાથે લિંક મોબાઈલ', 'બેંક પાસબુક'],
    popular: true
  },
  {
    id: 'driving-license',
    categoryEn: 'Identity & Registration',
    categoryGu: 'ઓળખ અને નોંધણી',
    titleEn: 'Driving License',
    titleGu: 'ડ્રાઈવિંગ લાયસન્સ',
    iconName: 'FileCheck',
    descriptionEn: 'Learner license, driving license renewal, duplicate license.',
    descriptionGu: 'કાચું લાયસન્સ, પાકું લાયસન્સ, રીન્યુઅલ.',
    documentsEn: ['Aadhaar Card', 'Passport Photo', 'Age/Address Proof'],
    documentsGu: ['આધાર કાર્ડ', 'પાસપોર્ટ ફોટો', 'ઉંમર/સરનામાનો પુરાવો'],
    popular: false
  },
  {
    id: 'ayushman-card',
    categoryEn: 'Health & Insurance',
    categoryGu: 'આરોગ્ય અને વીમો',
    titleEn: 'Ayushman Card (PMJAY)',
    titleGu: 'આયુષ્માન કાર્ડ (PMJAY)',
    iconName: 'HeartPulse',
    descriptionEn: 'Ayushman Bharat Card enrollment and printing.',
    descriptionGu: 'આયુષ્માન ભારત કાર્ડ કઢાવવા અને પ્રિન્ટ કરવા.',
    documentsEn: ['Aadhaar Card', 'Ration Card', 'Income Certificate (if applicable)'],
    documentsGu: ['આધાર કાર્ડ', 'રેશન કાર્ડ', 'આવકનો દાખલો (જો હોય તો)'],
    popular: true
  },
  {
    id: 'e-shram-card',
    categoryEn: 'Government Documents',
    categoryGu: 'સરકારી ડોક્યુમેન્ટ્સ',
    titleEn: 'E-Shram Card',
    titleGu: 'ઇ-શ્રમ કાર્ડ',
    iconName: 'Users',
    descriptionEn: 'E-Shram card registration for unorganized workers.',
    descriptionGu: 'અસંગઠિત કામદારો માટે ઇ-શ્રમ કાર્ડ નોંધણી.',
    documentsEn: ['Aadhaar Card', 'Aadhaar Linked Mobile', 'Bank Passbook'],
    documentsGu: ['આધાર કાર્ડ', 'આધાર સાથે લિંક મોબાઈલ', 'બેંક પાસબુક'],
    popular: false
  },
  {
    id: 'gst-registration',
    categoryEn: 'Financial & Business',
    categoryGu: 'નાણાકીય અને વ્યાપારી',
    titleEn: 'GST Registration & Return',
    titleGu: 'GST નોંધણી અને રિટર્ન',
    iconName: 'Calculator',
    descriptionEn: 'New GST number registration and monthly/quarterly returns.',
    descriptionGu: 'નવો GST નંબર મેળવવા અને માસિક/ત્રિમાસિક રિટર્ન ભરવા.',
    documentsEn: ['PAN Card', 'Aadhaar Card', 'Bank Details', 'Business Proof'],
    documentsGu: ['પાન કાર્ડ', 'આધાર કાર્ડ', 'બેંકની વિગતો', 'ધંધાનો પુરાવો'],
    popular: false
  },
  {
    id: 'msme-udyam',
    categoryEn: 'Financial & Business',
    categoryGu: 'નાણાકીય અને વ્યાપારી',
    titleEn: 'MSME / Udyam Registration',
    titleGu: 'ઉદ્યોગ આધાર / MSME',
    iconName: 'Building',
    descriptionEn: 'Udyam registration for small and medium enterprises.',
    descriptionGu: 'નાના અને મધ્યમ ઉદ્યોગો માટે ઉદ્યોગ આધાર નોંધણી.',
    documentsEn: ['Aadhaar Card', 'PAN Card', 'Bank Account Details'],
    documentsGu: ['આધાર કાર્ડ', 'પાન કાર્ડ', 'બેંક ખાતાની વિગતો'],
    popular: false
  },
  {
    id: 'police-clearance',
    categoryEn: 'Government Documents',
    categoryGu: 'સરકારી ડોક્યુમેન્ટ્સ',
    titleEn: 'Police Clearance Certificate',
    titleGu: 'પોલીસ ક્લિયરન્સ (PCC)',
    iconName: 'Shield',
    descriptionEn: 'Apply for Police Clearance Certificate for abroad travel or job.',
    descriptionGu: 'વિદેશ જવા કે નોકરી માટે પોલીસ ક્લિયરન્સ સર્ટિફિકેટ.',
    documentsEn: ['Aadhaar Card', 'Passport', 'Passport Photo'],
    documentsGu: ['આધાર કાર્ડ', 'પાસપોર્ટ', 'પાસપોર્ટ ફોટો'],
    popular: false
  },
  {
    id: 'food-license',
    categoryEn: 'Financial & Business',
    categoryGu: 'નાણાકીય અને વ્યાપારી',
    titleEn: 'FSSAI Food License',
    titleGu: 'ફૂડ લાયસન્સ (FSSAI)',
    iconName: 'Utensils',
    descriptionEn: 'Food license registration for food businesses.',
    descriptionGu: 'ખાણી-પીણી ના ધંધા માટે ફૂડ લાયસન્સ નોંધણી.',
    documentsEn: ['Aadhaar Card', 'Photo', 'Business Premises Proof'],
    documentsGu: ['આધાર કાર્ડ', 'ફોટો', 'ધંધાના સ્થળનો પુરાવો'],
    popular: false
  }
];
`;
fs.writeFileSync('src/data.ts', content, 'utf8');
